hawkular:
  url: https://yzamir-centos7-1.eng.lab.tlv.redhat.com:443
  username: hawkular
  password: aM0tVkm81he_ovm
  tenant: _ops
tags:
  - regex: .*
    type: node
    hostname: example.com
  - regex: memory
    units: byte
  - regex: cpu
    units: cpu
